services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB:   hotel_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "4000:5432"
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8888:8080"
    environment:
      SPRING_DATASOURCE_URL:     jdbc:postgresql://db:5432/hotel_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
